#' define_celltypes
#'
#' @description Define celltypes of selected phenotypes. If the specified phenotype vector is 
#' shorter than the phenotypes in the sce_object, then the unspecified phenotypes will be defined
#' as "Undefined" 
#' @param sce_object SingleCellExperiment object generated by format_image_to_sce
#' @param phenotypes Vector of phenotypes of keep or exclude; if NULL, the function will use 
#' predefined phenotypes and names
#' @param names Vector of new names assigned to the selected phenotypes; if NULL, 
#' the function will use predefined phenotypes and names
#' @export

define_celltypes <- function(sce_object,phenotypes = NULL, names = NULL){
  
  # default setting
  if (is.null(phenotypes) & is.null(names)){
    pre_phenotypes <- c("AMACR", "CD3,CD4", "CD3,CD8", "CD3", "AMACR,PDL-1","PDL-1")
    pre_names <- c("Tumour","CD4","CD8","CD3","Tumour,PDL1","PDL1")
  }
  
  else{
    pre_phenotypes <- phenotypes
    pre_names <- names
  }
  
  all_phenotypes <- unique(colData(sce_object)$Phenotype)
  phenotypes <- intersect(all_phenotypes, pre_phenotypes)
  names <- pre_names[match(phenotypes, pre_phenotypes)]
  print(phenotypes)
  print(names)
  
  sce_object$Cell.Type <- ""
  names<- c(names,rep("Undefined",length(all_phenotypes[!(all_phenotypes %in% phenotypes)])))
  phenotypes <- c(phenotypes,all_phenotypes[!(all_phenotypes %in% phenotypes)])
  for (i in 1:length(phenotypes)){
    sce_object[,sce_object$Phenotype == phenotypes[i]]$Cell.Type <- names[i]
  }
  
  
  return(sce_object)
}

