#' define_phenotypes
#'
#' @description Define phenotypes of selected cells
#' @param sce_object SingleCellExperiment object generated by format_image_to_sce
#' @param phenotypes Vector of phenotypes of keep or exclude
#' @param names Vector of new names assigned to the selected phenotypes
#' @export

define_phenotypes <- function(sce_object,phenotypes = NULL, names = NULL){
  # CHECK if a phenotype not exist
  if (!all(phenotypes %in% unique(colData(sce_object)$Phenotype))){
    stop("One or more phenotype not found in image")
  }
  sce_object <- sce_object[,sce_object$Phenotype %in% phenotypes]
  for (i in 1:length(phenotypes)){
    sce_object[,sce_object$Phenotype == phenotypes[i]]$Phenotype <- names[i]
  }
  return(sce_object)
}

