#' define_celltypes
#'
#' @description Define celltypes of selected categories. If the specified category vector is 
#' shorter than the categories in the sce_object, then the unspecified categories will be defined
#' as "Undefined" 
#' @param sce_object SingleCellExperiment object generated by format_image_to_sce
#' @param categories Vector of categories to be defined; if NULL, the function will use 
#' predefined categories and names
#' @param category_colname (Optional) String specifying the name of the column 
#' having the categories to be defined, by default "Phenotype"
#' @param names Vector of new names assigned to the selected categories; if NULL, 
#' the function will use predefined categories and names
#' @param new_colname (Optional) String specifying the name of the column to be added, by default "Cell.Type"
#' @export

define_celltypes <- function(sce_object,categories = NULL, category_colname = "Phenotype",
                             names = NULL, new_colname = "Cell.Type"){
  
  # default setting
  if (is.null(categories) & is.null(names)){
    pre_categories <- c("AMACR", "CD3,CD4", "CD3,CD8", "CD3", "AMACR,PDL-1","PDL-1")
    pre_names <- c("Tumour","CD4","CD8","CD3","Tumour,PDL1","PDL1")
  }
  
  else{
    pre_categories <- categories
    pre_names <- names
  }
  
  all_categories <- unique(colData(sce_object)[[category_colname]])
  categories <- intersect(all_categories, pre_categories)
  names <- pre_names[match(categories, pre_categories)]
  print(categories)
  print(names)
  
  sce_object[[new_colname]] <- ""
  names<- c(names,rep("Undefined",length(all_categories[!(all_categories %in% categories)])))
  categories <- c(categories,all_categories[!(all_categories %in% categories)])
  for (i in 1:length(categories)){
    sce_object[,sce_object[[category_colname]] == categories[i]][[new_colname]] <- names[i]
  }
  
  
  return(sce_object)
}

