#' print_feature
#'
#' @description Print the unique values of a specified column (feature)
#' @param sce_object SingleCellExperiment object generated by format_image_to_sce
#' @param column String of the specified column
#' @return A character vector is returned
#' @examples
#' print_phenotypes(SPIAT::formatted_image)
#' @export

print_feature <- function(sce_object, column){
  print(unique(colData(sce_object)[[column]]))
}