#' print_phenotypes
#'
#' @description Prints phenotypes that are present in the sample
#' @param sce_object SingleCellExperiment object generated by format_image_to_sce
#' @examples
#' print_phenotypes(SPIAT::formatted_image)
#' @export

print_phenotypes <- function(sce_object){
 print(unique(colData(sce_object)$Phenotype))
}
