#' print_column
#'
#' @description Print the unique values of a specified column
#' @param sce_object SingleCellExperiment object generated by format_image_to_sce
#' @param column String of the specified column
#' @return A character vector is returned
#' @export

print_column <- function(sce_object, column){
  print(unique(colData(sce_object)[[column]]))
}
