#' print_feature
#'
#' @description Print the unique values of a specified column (feature)
#' @param sce_object SingleCellExperiment object generated by format_image_to_sce
#' @param feature_colname String of the specified column
#' @return A character vector is returned
#' @examples
#' feature_colname <- "Phenotype"
#' print_phenotypes(SPIAT::formatted_image, feature_colname)
#' @export

print_feature <- function(sce_object, feature_colname){
  print(unique(colData(sce_object)[[feature_colname]]))
}