#' select_celltypes
#'
#' @description Select celltypes to keep or exclude in the analysis
#' @param sce_object SingleCellExperiment object generated by format_image_to_sce
#' @param celltypes Vector of celltypes of keep or exclude
#' @param column String the name of the column that the celltypes are under
#' @param keep TRUE if vector of phenotypes are the cells that are going to be kept,
#' FALSE if they are to be removed
#' @return A SingleCellExperiment object is returned
#' @examples
#' data_subset <- select_celltypes(SPIAT::formatted_image,
#'                                 celltypes = c("AMACR","CD3,CD8","PDL-1"), 
#'                                 column = "Phenotype, keep=TRUE)
#' @export
select_celltypes <- function(sce_object, celltypes, column = "Phenotype", keep = TRUE){
  data <- data.frame(colData(sce))
  # remember the total number of cells
  n_cells <- dim(data)[1]
  # remember the range of the cell coordinates
  xmax <- max(data$Cell.X.Position)
  xmin <- min(data$Cell.X.Position)
  ymax <- max(data$Cell.Y.Position)
  ymin <- min(data$Cell.Y.Position)
  
  # delete the cell rows (not sure if this affects anything)
  if (keep) slim_sce <- sce[, (sce[[column]] %in% celltypes)]
  else slim_sce <- sce[, !(sce[[column]] %in% celltypes)]
  
  # save the original image info in the slim attr
  attr(slim_sce, "original_cell_number") <- n_cells
  attr(slim_sce, "range_of_coords") <- c(xmin, xmax, ymin, ymax)
  
  return(slim_sce)
}
