#' select_celltypes
#'
#' @description Select cell types to keep or exclude in the analysis. This
#'   function remembers the original image size and cell count.
#'
#' @param sce_object SingleCellExperiment object generated by
#'   format_image_to_sce.
#' @param celltypes String Vector of celltypes of keep or exclude.
#' @param feature_colname String. The column that has the interested cell types.
#' @param keep Boolean. TRUE if vector of `celltypes` are the cells that are
#'   going to be kept, FALSE if they are to be removed.
#' @return A SingleCellExperiment object is returned. The original image size
#'   and cell count can be accessed by `attr(slim_sce, "original_cell_number")`
#'   and `attr(slim_sce, "range_of_coords")`.
#' @examples
#' data_subset <- select_celltypes(SPIAT::simulated_image,
#' celltypes = c("Tumour_marker","Immune_marker1","Immune_marker2","Immune_marker3","Immune_marker4"),
#' feature_colname = "Phenotype", keep=TRUE)
#' attr(data_subset, "original_cell_number") #cell number in the original image
#' attr(data_subset, "range_of_coords") 
#' dim(data_subset)[2] # this is the new image cell number
#' @export
select_celltypes <- function(sce_object, celltypes, 
                             feature_colname = "Phenotype", keep = TRUE){
  data <- data.frame(SummarizedExperiment::colData(sce_object))
  # remember the total number of cells
  n_cells <- dim(data)[1]
  # remember the range of the cell coordinates
  xmax <- max(data$Cell.X.Position)
  xmin <- min(data$Cell.X.Position)
  ymax <- max(data$Cell.Y.Position)
  ymin <- min(data$Cell.Y.Position)
  
  # delete the cell rows (not sure if this affects anything)
  if (keep) slim_sce <- sce_object[, (sce_object[[feature_colname]] %in% celltypes)]
  else slim_sce <- sce_object[, !(sce_object[[feature_colname]] %in% celltypes)]
  
  # save the original image info in the slim attr
  attr(slim_sce, "original_cell_number") <- n_cells
  attr(slim_sce, "range_of_coords") <- c(xmin, xmax, ymin, ymax)
  
  return(slim_sce)
}
